### ISSUE TITLE
How can I upload an image to a specific folder of bucket?

### ISSUE THREAD

**Issue by ahelord** [jgpacheco/ngx-s3-uploader#10]
How can I upload an image to a bucket folder, for example mybucket / image-profile / me.png

**Comment by jgpacheco** [comment]
According to AWS documentation: 

> To put an object in a specific folder you should prefix the object key with the folder you want the object in.

But [we are using file name only as file name](https://github.com/jgpacheco/ngx-s3-uploader/blob/master/src/s3-uploader.service.ts#L72) .PRs are welcome. :)

**Comment by jgpacheco** [comment]
Tracked in: [#13](https://github.com/jgpacheco/ngx-s3-uploader/issues/13)
