### ISSUE TITLE
Not working with Angular 6

### ISSUE THREAD

**Issue by Antonyselt** [jgpacheco/ngx-s3-uploader#14]
when I installed the package the ng serve give me and error about Rxjs, I imagine is because the new version of Rxjs is different from the one you use

**Comment by jgpacheco** [comment]
@Antonyselt Thank you for filing the issue. I rebuild the library using [Angular v6 CLI library support](https://github.com/angular/angular-cli/wiki/stories-create-library) and worked fine after RxJS v6  migration. Would be great if you could test it too before publishing to npm. https://drive.google.com/file/d/1HkCd5UoH5evdZvgLQqM7SWp-BPexaBbx/view?usp=sharing

**Comment by Antonyselt** [comment]
I will, thank you.

**Comment by Antonyselt** [comment]
@jgpacheco Hi!

Maybe is poor configuration on my part but I wasn't able to se the button
![captura de pantalla 19](https://user-images.githubusercontent.com/13181287/42672776-8dd46d56-862d-11e8-959f-124e66750b85.png)

Will be possible if you can give me a new app with the new version of the plugin so I can rebuild in mi laptop when I can tested

**Comment by jgpacheco** [comment]
@Antonyselt Thank you for testing. [s3-uploader](https://github.com/jgpacheco/ngx-s3-uploader/blob/master/src/s3-uploader.component.ts#L8) component adds an input with `display: none;`.

Try putting something inside (it uses transclusion):
```
  <s3-uploader (success)="avatarUploaded($event)" (error)="avatarUploadError($event)">
    <img width="300" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
  </s3-uploader>
```

I used this [repo ](https://github.com/jgpacheco/ng6-s3-uploader) for testing.

**Comment by Antonyselt** [comment]
Ok thank you, I will try out again. Thank you so much for you support

**Comment by jgpacheco** [comment]
@Antonyselt Any update?

**Comment by jgpacheco** [comment]
Package generated with Angular 6 built-in library support: https://www.npmjs.com/package/ng6-s3-uploader

**Comment by Antonyselt** [comment]
Sorry  @jgpacheco work is killing me, I would try it this weekend the plugin, thank you.
