### ISSUE TITLE
OpaqueToken issue in ngx-s3-uploader 

### ISSUE THREAD

**Issue by ghost** [jgpacheco/ngx-s3-uploader#4]
ERROR in node_modules/ngx-s3-uploader/s3-uploader.service.d.ts(1,10): error TS2305: Module '"/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.     >>>>  i got this issue in angular5 , can you please give some solution for this issue

**Comment by jgpacheco** [comment]
OpaqueToken was removed in Angular 5. An upgrade is required.

**Comment by jgpacheco** [comment]
@aarustar https://github.com/jgpacheco/ngx-s3-uploader/blob/master/CHANGELOG.md#fixed
