### ISSUE TITLE
What options there is 'ACL_TO_APPLY'?

### ISSUE THREAD

**Issue by ahelord** [jgpacheco/ngx-s3-uploader#7]
Hi excellent library, I do not understand what I should put in or what options there is 'ACL_TO_APPLY'

**Comment by jgpacheco** [comment]
Thank you @ahelord. 
Possible values for `ACL_TO_APPLY` are ([according to AWS.S3 documentation](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property)):
"private"
"public-read"
"public-read-write"
"authenticated-read"
"aws-exec-read"
"bucket-owner-read"
"bucket-owner-full-control"
